### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by robmarkcole** [EverythingSmartHome/mlx90640-thermal-camera#1]
How did you get on with this melexsis? I found some annoying issues when using it, related to the readout which put a checkerboard pattern on the readout.

I was going to suggest you could integrate it to HA with MQTT like in https://github.com/robmarkcole/mqtt-camera-streamer

This would be a nice complement to camera approach for accurate people detection

**Comment by EverythingSmartHome** [comment]
I haven't used the Melexsis brand specifically, mine was from Pimoroni which worked well. Was the checkerboard related to the software you were using or the camera?

Yeah that could be a nice integration, most likely beyond my capabilities!

**Comment by robmarkcole** [comment]
Pimoroni are using the melexsis sensor. The issue is https://github.com/pimoroni/mlx90640-library/issues/23
I didnt touch the device since experiencing this issue
